name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Private Registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: yadav-${{ github.run_id }}
          ECR_REPOSITORY: 342333476898.dkr.ecr.us-east-1.amazonaws.com
          ECR_IMAGE: github
        run: |
          sudo docker build -t yadav .
          sudo docker tag yadav:latest $ECR_REPOSITORY/$ECR_IMAGE:$IMAGE_TAG
          sudo docker push $ECR_REPOSITORY/$ECR_IMAGE:$IMAGE_TAG
